version: 2.1

orbs:
  unity: game-ci/unity@1.7

jobs:
  checkout:
    executor:
      name: 'unity/windows-2022'
      size: 'large'
      editor_version: '2023.1.13f1'
      target_platform: 'windows-il2cpp'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "af:18:8c:c4:0c:26:00:31:70:07:6a:01:4f:24:83:c9"
      - run:
        
      - checkout
      
workflows:
  test-unity-project:
    jobs:
      - checkout
      # Windows
      - unity/test:
          name: 'test-windows'
          step-name: 'Check if the tests run and results are uploaded'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2022'
            size: 'large'
            editor_version: '2021.3.2f1'
            target_platform: 'windows-il2cpp'
          project-path: 'Unity2D-Demo-Game-CI-CD/src'
          test-platform: 'playmode'
          context: unity
          requires:
            - checkout