version: 2.1

orbs:
  unity: game-ci/unity@1.7.0

workflows:
  ssh_key:
    jobs:
       steps:
        - add_ssh_key:
            fingerprints:
              - "38:26:c1:fd:dd:bd:b0:7b:1f:7a:1c:49:b8:2d:bd:68"

  test-unity-project:
    jobs:
      - unity/test:
          name: 'test-windows'
          step-name: 'Check if the tests run and results are uploaded'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2022'
            size: 'large'
            editor_version: '2023.1.13f1'
            target_platform: 'windows-il2cpp'
          project-path: 'TestCI/Assets'
          test-platform: 'playmode'
          context: unity