version: 2.1

orbs:
  unity: game-ci/unity@1.7

jobs:
  checkout:
    executor:
      name: 'unity/windows-2022'
      size: 'large'
      editor_version: '2023.1.13f1'
      target_platform: 'windows-il2cpp'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "38:26:c1:fd:dd:bd:b0:7b:1f:7a:1c:49:b8:2d:bd:68"
      - checkout
      
workflows:
  test-unity-project:
    jobs:
      - checkout
      - unity/build:
          name: 'build-Windows64-il2cpp'
          step-name: 'Build project for Windows using Cloud'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2019'
            size: 'large'
            editor_version: '2021.3.2f1'
            target_platform: 'windows-il2cpp'
          project-path: 'Unity2D-Demo-Game-CI-CD/src'
          build-target: StandaloneWindows64
          context: unity
          requires:
            - checkout