version: 2.1

orbs:
  unity: game-ci/unity@1.7.0

workflows:
  build-unity-project:
    jobs:
      - unity/build:
          name: 'build-linux64-il2cpp'
          step-name: 'Build StandaloneLinux64'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'linux-il2cpp'
            editor_version: '2023.1.13f1'
            resource_class: 'large'
          project-path: 'TestCI/Assets'
          build-target: StandaloneLinux64
          compress: true
          context: unity