version: 2.1

orbs:
  unity: game-ci/unity@1.7.0
      
workflows:
  create-unity-activation-file:
    jobs:
      - unity/create-activation-file
  test-unity-project:
    jobs:
      # Windows
      - unity/test:
          name: 'test-windows'
          step-name: 'Check if the tests run and results are uploaded'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2022'
            size: 'large'
            editor_version: '2021.3.2f1'
            target_platform: 'windows-il2cpp'
          test-platform: 'playmode'
          require:
            - create-unity-activation-file
