version: 2.1

orbs:
  unity: game-ci/unity@1.7.0
  windows: circle/windows@5.0.0

jobs:
  unity-test:
    description: unity test
    executor:
       name: unity/windows-2019
    steps:
      - add_ssh_keys:
          fingerprints:
            - "62:fd:4b:73:5b:b4:c1:45:88:e3:80:cc:ce:0b:c9:a9"
      - checkout
      - run:
          name: unity-create-cer
          command:
            - unity/create-activation-file:
                editor_version: "2023.1.13f1"


workflows:
  test-unity-project:
    jobs:
      - unity-test
